---
- name: restart keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted
    daemon_reload: yes
  listen: restart keycloak

- name: reload keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: reloaded
  listen: reload keycloak

- name: rebuild and restart keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted
    daemon_reload: yes
  listen: rebuild and restart keycloak